version: "3"
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./dataset:/app/dataset
      - ./dataset/audiofiles:/app/recordings
    environment:
      MongoClient: "mongodb://mongodb:27017"
      IP_AUDIO_SERVER: "http://localhost:8080/"
      PYTHONUNBUFFERED: 1
    ports:
      - 8000:8000
    depends_on:
      - mongodb
  
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      REACT_APP_IPAdress: "http://localhost:8000/"
    ports:
      - 3000:3000
    depends_on:
      - backend
  
  audioserver:
    image: httpd:2.4
    ports:
      - "8080:80"
    volumes:
      - ./dataset/audiofiles:/usr/local/apache2/htdocs/
  
  mongodb:
    image: mongo:latest

    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: